version: '3.9'
services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongodb_service
  mongodb_service:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: